trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'UbuntuVM'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/tmp/sample-app'

- task: SSH@0
  inputs:
    sshEndpoint: 'UbuntuVM'
    runOptions: 'commands'
    commands: |
      sudo cp /tmp/sample-app/index.html /var/www/html/index.html
      sudo systemctl restart nginx